// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5lA2ywkNYaECWk6Kjivih3oVNItHtrqI',
    appId: '1:72395756469:web:76fd444c8b281f995efffc',
    messagingSenderId: '72395756469',
    projectId: 'fruit-d5da6',
    authDomain: 'fruit-d5da6.firebaseapp.com',
    storageBucket: 'fruit-d5da6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArl04By63DDRb12iUzUHVaGGobfZz_3SQ',
    appId: '1:72395756469:android:788cd99c535b90335efffc',
    messagingSenderId: '72395756469',
    projectId: 'fruit-d5da6',
    storageBucket: 'fruit-d5da6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtxhnhvFx1QrINSd5-EOb8nE2tFYIcdCw',
    appId: '1:72395756469:ios:79ea68cb99bd68755efffc',
    messagingSenderId: '72395756469',
    projectId: 'fruit-d5da6',
    storageBucket: 'fruit-d5da6.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtxhnhvFx1QrINSd5-EOb8nE2tFYIcdCw',
    appId: '1:72395756469:ios:79ea68cb99bd68755efffc',
    messagingSenderId: '72395756469',
    projectId: 'fruit-d5da6',
    storageBucket: 'fruit-d5da6.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5lA2ywkNYaECWk6Kjivih3oVNItHtrqI',
    appId: '1:72395756469:web:91a9d813bc48f3905efffc',
    messagingSenderId: '72395756469',
    projectId: 'fruit-d5da6',
    authDomain: 'fruit-d5da6.firebaseapp.com',
    storageBucket: 'fruit-d5da6.firebasestorage.app',
  );
}
